# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], max_length=1),
        ),
    ]
