# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_product_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='length',
            new_name='size',
        ),
    ]
