# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20170430_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], max_length=1, verbose_name='tamanho'),
        ),
    ]
